# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Put Option'), (2, 'Call Option')])),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='currency',
            field=models.IntegerField(choices=[(1, 'Israeli Shekel'), (2, 'European Euro'), (3, 'USD'), (4, 'Swiss Frank'), (5, 'British Pound')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='industry',
            field=models.IntegerField(choices=[(1, 'Pharma'), (2, 'Hi-Tech')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_tradable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='rating',
            field=models.IntegerField(choices=[(0, 'UNDEFINED'), (1, 'D'), (2, 'C'), (3, 'CC'), (4, 'CCC-'), (5, 'CCC'), (6, 'CCC+'), (7, 'B-'), (8, 'B'), (9, 'B+'), (10, 'BB-'), (11, 'BB'), (12, 'BB+'), (13, 'BBB-'), (14, 'BBB'), (15, 'BBB+'), (16, 'A-'), (17, 'A'), (18, 'A+'), (19, 'AA-'), (20, 'AA'), (21, 'AA+'), (22, 'AAA')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundmanagingbody',
            name='managing_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pension.Issuer'),
        ),
        migrations.DeleteModel(
            name='ManagingBody',
        ),
        migrations.AddField(
            model_name='derivative',
            name='base_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pension.Instrument'),
        ),
        migrations.AddField(
            model_name='derivative',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Derivative_Extension', to='pension.Instrument'),
        ),
    ]
